### ISSUE TITLE
Load surfaces

### ISSUE THREAD

**Issue by Leguark** [softwareunderground/subsurface#22]

**Comment by MonEstCha** [comment]
I thought about writing a generic script for reading in any surface related csv file to a DataFrame and/or xarray, so that the number of columns doesn't matter., i.e. if the csv contains only vertices or vertices with attributes. What do you think?

**Comment by Leguark** [comment]
Yes, that would be great. As long as the output is an UnstructuredData object, the more we can do for the user the better :D

**Comment by MonEstCha** [comment]
Okay, then for examples I create a PointSet class object, if only vertices are listed in the csv, or a TriSurf object, if edges are present, instead of just the DataFrame?

**Comment by MonEstCha** [comment]
I'm getting warnings with my latest commit, test_surface_reader.test_plot_to_pyvista (line 52) and commented that at the mentioned line as a review
