### ISSUE TITLE
Welly : AttributeError: 'NoneType' object has no attribute 'position'

### ISSUE THREAD

**Issue by Japhiolite** [softwareunderground/subsurface#57]
Transfered [Issue 681 from the gempy repository](https://github.com/cgre-aachen/gempy/issues/681).

User @neha845 reported an `AttributeError` when trying to read in a welly project via subsurface:

**The class WellyToSubsurfaceHelper contains the methods to create a welly project and export it to a subsurface data class.**
Error in the following line of code.
wts = sb.reader.wells.WellyToSubsurfaceHelper(collar_df=collar, survey_df=survey, lith_df=lith)

**Screenshots**
<img width="824" alt="image" src="https://user-images.githubusercontent.com/56668663/157988337-3b1d0133-7b45-45fa-896d-199fe02729e9.png">

**Desktop (please complete the following information):**
  * OS: Windows
  * GemPy Version - 2.2.10

**Trying on the same dataset as provided in the t21 tutorial - kim_ready.csv**
https://github.com/cgre-aachen/gempy_workshops/blob/33e4f8651250494c1e76f4c7149aa8a021ce5ddb/workshops/Transform2021/t21_gempy.ipynb

**Comment by neha845** [comment]
@Japhiolite , no update yet.

**Comment by Japhiolite** [comment]
Hi @neha845 

the created well object `w` seems to be empty in your example (that's why it's `NoneType`). 
What is your version of welly?
It may also be, that subsurface has to be updated in that regard, as `position` is now moved to `location.position` in welly, I think.

**Comment by Japhiolite** [comment]
This may indeed be a bug in subsurface. 
I'll have a look into it.

**Comment by neha845** [comment]
> This may indeed be a bug in subsurface. I'll have a look into it.

Sure

**Comment by neha845** [comment]
Hey @Japhiolite 
Is there any update in the issue?
Kindly help.

**Comment by Japhiolite** [comment]
Hi @neha845 

I implemented a change in PR #58 .

However, from your screenshot, I noticed that your welly object seems to be empty (not initialized correctly?), as it shows `Nonetype`.
could you maybe provide  the collar, survey, lith dataframes? Then I could check.

**Comment by neha845** [comment]
Sure, pls see the screenshots attached.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/56668663/160480830-8858313f-1ac3-45ad-9d5b-769b75d6c517.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/56668663/160481099-402f4eeb-5d02-442b-b1aa-480ef9c35593.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/56668663/160481173-0a7d337c-a18f-4e44-a404-dc7dce266677.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/56668663/160481295-cd41ed36-d7d2-4a25-b507-9e2fbafc4775.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/56668663/160481413-37b0c131-05fe-41ad-8129-0b09f27b6b68.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/56668663/160481509-172a74f3-1045-4c39-8d7d-c3f47640d2b8.png">

Data used is same as provided in the T21 tutorial - https://raw.githubusercontent.com/softwareunderground/subsurface/main/tests/data/borehole/kim_ready.csv

**Comment by neha845** [comment]
Hi, @Japhiolite 
Pls see.

**Comment by Japhiolite** [comment]
Hi @neha845 

Ah, didn't know it was the T21 tutorial. I've tested the tutorial notebook, and indeed it raises the error with welly version 0.5.2.

With version 0.5.0, the welly team reworked a good chunk of their code, so there may be some substantial changes to be made to subsurface.

If you downgrade welly to version 0.4.8, the T21 tutorial should work. At least it worked for me, when welly was downgraded to a version < 0.5. Hope that helps.

**Comment by Japhiolite** [comment]
I remember this error. `from_dict_advanced` was a method developed by @Leguark in Striplog. But that method did not make it in the striplog pip-release. It is referenced in his fork from striplog: https://github.com/Leguark/striplog 

For making the Transform 2021 notebook work, you'd have to use the striplog version from Leguark. Best would be to create a new pyhton-environment (e.g. cloning your current one) and there use `pip install git+https://github.com/Leguark/striplog.git`.
Then you would use the changed striplog version, which is, however, outdated compared to the main by Agile\*.

**Comment by neha845** [comment]
Hi @Japhiolite 
It worked like magic. 
Thank you for your help. :)

Now, going to try with custom dataset.

**Comment by Japhiolite** [comment]
Great to hear :)
