### ISSUE TITLE
GemPy no longer outputs Xarray structured grids

### ISSUE THREAD

**Issue by andieie** [softwareunderground/subsurface#72]
Hi there. I am trying to recreate this [example ](https://htmlpreview.github.io/?https://raw.githubusercontent.com/andieie/t21_hacksubsurface/main/gempy_to_pygimli.html) with the new version of GemPy(2.3.1) and this no longer exists `gempymesh = model.s_regular_grid`. I have found `geomodel.solutions.grids.regular_grids` as an alternative but it is no longer in Xarray format. Is this under another name? Do I have to manually turn it into an xarray object? I heard @Leguark has been working with some meshing recently and maybe this changed in the latest version of GemPy. Would really appreciate your help! 

Thank you !

**Comment by andieie** [comment]
I just saw the release of GemPy 3 with more changes. I will close this issue and update with the new structure.

**Comment by Leguark** [comment]
Thanks Andrea! 

Those type of integrations now fit better as a gempy_plugin (https://github.com/gempy-project/gempy_plugins). You can directly make a pull request to it or send me the example working and I will publish it.
