### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by stevejpurves** [softwareunderground/subsurface#9]
I am setting up a conda environment and then using the requirements.txt to setup dependencies but the command fails due to the dependency `python==3.7` dep. I don't usually list python as a dep. should we remove that?

**Comment by pytzcarraldo** [comment]
I've removed python from the requirements.txt - hope it works now for you!

**Comment by stevejpurves** [comment]
got it and installed 👍  thanks!
